//
//  TransactionListViewController.swift
//  BudTransaction
//
//  Created by Godfrey Bagley-Clarke on 29/06/2018.
//  Copyright (c) 2018 Godfrey Bagley-Clarke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TransactionListDisplayLogic: class {
    func displaySomething(viewModel: TransactionList.Something.ViewModel)
}

class TransactionListViewController: UIViewController, TransactionListDisplayLogic, UITableViewDataSource, UITableViewDelegate {
    @IBOutlet weak var loadingView: UIView!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var tableView: UITableView!
    var interactor: TransactionListBusinessLogic?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = TransactionListInteractor()
        let presenter = TransactionListPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let gb = GradientBackground()
        gb.setGradientBackground(view: self.view)
        doSomething()
    }
    
    // MARK: Do something
    
    func doSomething() {
        loadingView.isHidden = false
        activityIndicator.startAnimating()
        tableView.isHidden = true
        let request = TransactionList.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: TransactionList.Something.ViewModel) {
        activityIndicator.stopAnimating()
        loadingView.isHidden = true
        tableView.isHidden = false
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 16
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "TransactionTableViewCell") as! TransactionTableViewCell
        configureCell(cell: cell)
        return cell
    }
    
    func configureCell(cell: TransactionTableViewCell) {
        cell.iconImageView.layer.cornerRadius = cell.iconImageView.frame.size.width / 2
        cell.iconImageView.clipsToBounds = true
        cell.valueLabel.sizeToFit()
        cell.valueWidthConstraint.constant += 15
        view.layoutIfNeeded()
    }
}
