//
//  TransactionListViewController.swift
//  BudTransaction
//
//  Created by Godfrey Bagley-Clarke on 29/06/2018.
//  Copyright (c) 2018 Godfrey Bagley-Clarke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

protocol TransactionListDisplayLogic: class {
    func displayTransactions(viewModel: TransactionList.Index.ViewModel)
}

class TransactionListViewController: UIViewController, TransactionListDisplayLogic, UITableViewDataSource, UITableViewDelegate {
    @IBOutlet weak var loadingView: UIView!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var tableView: UITableView!
    var interactor: TransactionListBusinessLogic?
    var transactions = [TransactionList.Index.Transaction]()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = TransactionListInteractor()
        let presenter = TransactionListPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let gb = GradientBackground()
        gb.setGradientBackground(view: self.view)
        tableView.tableFooterView = UIView()
        getTransactions()
    }
    
    // MARK: Do something
    
    func getTransactions() {
        loadingView.isHidden = false
        activityIndicator.startAnimating()
        tableView.isHidden = true
        let request = TransactionList.Index.Request(version: "v2", uniqueId: "5b33bdb43200008f0ad1e256")
        interactor?.fetchTransactions(request: request)
    }
    
    func displayTransactions(viewModel: TransactionList.Index.ViewModel) {
        
        if Thread.isMainThread {
            self.activityIndicator.stopAnimating()
            self.loadingView.isHidden = true
            self.tableView.isHidden = false
            self.transactions = viewModel.transactions
            self.tableView.reloadData()
        } else {
            DispatchQueue.main.async {
                self.activityIndicator.stopAnimating()
                self.loadingView.isHidden = true
                self.tableView.isHidden = false
                self.transactions = viewModel.transactions
                self.tableView.reloadData()
            }
        }
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 65.0
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return transactions.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "TransactionTableViewCell") as! TransactionTableViewCell
        populateCell(cell: cell, row: indexPath.row)
        configureCell(cell: cell)
        return cell
    }
    
    func configureCell(cell: TransactionTableViewCell) {
        cell.iconImageView.layer.cornerRadius = cell.iconImageView.frame.size.width / 2
        cell.iconImageView.clipsToBounds = true
    }
    
    func populateCell(cell: TransactionTableViewCell, row: Int) {
        cell.iconImageView.sd_setImage(with: URL(string: transactions[row].product.icon))
        cell.descriptionLabel.text = transactions[row].description.capitalized
        cell.valueLabel.text = getFormatForCurrencyCode(code: transactions[row].amount.currency_iso, value: transactions[row].amount.value as NSNumber)
        let dateParts = transactions[row].date.components(separatedBy: "-")
        cell.dateLabel.text = String("\(dateParts[2])/\(dateParts[1])/\(dateParts[0])")
    }
    
    func getFormatForCurrencyCode(code: String, value: NSNumber) -> String? {
        let currencyFormatter = NumberFormatter()
        currencyFormatter.numberStyle = .currency
        currencyFormatter.currencyCode = code
        return currencyFormatter.string(from: value)
    }

    @IBAction func refreshTransactions(_ sender: Any) {
        getTransactions()
    }
}
