//
//  TransactionListModels.swift
//  BudTransaction
//
//  Created by Godfrey Bagley-Clarke on 29/06/2018.
//  Copyright (c) 2018 Godfrey Bagley-Clarke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TransactionList {
    enum Index {
        struct Request {
            var version: String?
            var uniqueId: String?
        }
        struct Response: Decodable {
            let data: [Transaction]
        }

        struct Transaction: Decodable {
            let date: String
            let description: String
            let amount: Amount
            let product: Product
        }
        
        struct Amount: Decodable {
            let value: Double
            let currency_iso: String
        }
        struct Product: Decodable {
            let icon: String
        }

        struct ViewModel: Decodable {
            let transactions: [Transaction]
            var errorMessage: String?
        }
    }
}
