//
//  TransactionListPresenter.swift
//  BudTransaction
//
//  Created by Godfrey Bagley-Clarke on 29/06/2018.
//  Copyright (c) 2018 Godfrey Bagley-Clarke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TransactionListPresentationLogic {
    func presentTransactions(response: TransactionList.Index.Response)
}

class TransactionListPresenter: TransactionListPresentationLogic {
    weak var viewController: TransactionListDisplayLogic?
    
    func presentTransactions(response: TransactionList.Index.Response) {
        let viewModel = TransactionList.Index.ViewModel(transactions: response.data, errorMessage: "")
        viewController?.displayTransactions(viewModel: viewModel)
    }
}
