//
//  TransactionListPresenter.swift
//  BudTransaction
//
//  Created by Godfrey Bagley-Clarke on 29/06/2018.
//  Copyright (c) 2018 Godfrey Bagley-Clarke. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TransactionListPresentationLogic {
    func presentSomething(response: TransactionList.Something.Response)
}

class TransactionListPresenter: TransactionListPresentationLogic {
    weak var viewController: TransactionListDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: TransactionList.Something.Response) {
        let viewModel = TransactionList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
